### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [amitx-npm/number-with-ordinal#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by amitpanigrahi** [comment]
@geopic ,

Thanks for your suggestion. But I am not sure how its gonna help. And which issue it will address to.

**Comment by amitpanigrahi** [comment]
> If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by geopic** [comment]
Ok, no problem. :smile:
